#!/usr/bin/env python3
"""
Generator for the theme-factory-addon theme library.

Authors a single source-of-truth data table and emits one Markdown file per
theme into ./themes/, matching the upstream theme-factory file format exactly:

    # Theme Name
    <one-line description>
    ## Color Palette   (- **Name**: `#hex` - role)
    ## Typography      (- **Headers**: ...  - **Body Text**: ...)
    ## Best Used For

Color *roles* are assigned automatically by relative luminance so the palette
always reads lightest -> darkest (background -> text), regardless of the order
the source listed them in.

Sources (palettes lifted verbatim, names/roles/fonts added here):
  - The Brand Alchemists, "24 Aesthetic Colour Palettes" (Earthy, Feminine,
    Coastal, Bold, Modern Boho, Vintage Romance)
  - Steph Corrigan Design, "10 Sophisticated Colour Palettes for Luxury Branding"

Run:  python3 generate_themes.py
"""

import os
import re

THEMES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "themes")

# Role ladders by palette size. For light themes colors run lightest -> darkest
# (background -> text); for dark themes they run darkest -> lightest
# (background -> foreground).
ROLE_LADDERS = {
    6: ["Base / background", "Light neutral", "Soft accent",
        "Mid-tone accent", "Deep accent", "Anchor / text"],
    5: ["Base / background", "Light neutral", "Accent",
        "Deep accent", "Anchor / text"],
    4: ["Base / background", "Light accent", "Deep accent", "Anchor / text"],
}
DARK_LADDERS = {
    6: ["Base / background", "Surface", "Muted accent",
        "Accent", "Bright accent", "Foreground / text"],
    5: ["Base / background", "Surface", "Accent",
        "Bright accent", "Foreground / text"],
    4: ["Base / background", "Accent", "Bright accent", "Foreground / text"],
}
LADDERS = {"light": ROLE_LADDERS, "dark": DARK_LADDERS}


def luminance(hex_code):
    """Relative luminance (0=dark, 1=light) for sorting."""
    h = hex_code.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def slugify(name):
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s


# Each theme: (name, description, category, [(color_name, hex), ...], best_for)
# Fonts are assigned per-category below.
CATEGORY_FONTS = {
    "Earthy & Grounded":        ("Fraunces", "Karla"),
    "Feminine & Soft":          ("Cormorant Garamond", "Nunito Sans"),
    "Coastal & Calm":           ("Quicksand", "Open Sans"),
    "Bold & Fun":               ("Poppins", "Work Sans"),
    "Modern Boho & Neutrals":   ("Marcellus", "Mulish"),
    "Vintage Romance":          ("Playfair Display", "EB Garamond"),
    "Luxury & Sophisticated":   ("Bodoni Moda", "Montserrat"),
    "Iconic Brands":            ("Montserrat", "Work Sans"),
    "Editor Classics (Dark)":   ("JetBrains Mono", "Inter"),
    "Editor Light":             ("Fira Code", "Inter"),
    "Neon & Retro":             ("Space Mono", "Inter"),
    "Obsidian & Calm":          ("IBM Plex Mono", "IBM Plex Sans"),
    "Master Painters":          ("Cormorant Garamond", "Spectral"),
    "Directors & Cinematographers": ("Oswald", "Barlow"),
}

THEMES = [
    # ---------------- Earthy & Grounded ----------------
    ("Mountain Air",
     "Crisp alpine air over deep pine and slate — grounded yet open.",
     "Earthy & Grounded",
     [("Glacier Mist", "#D4E1E7"), ("Sky Wash", "#99BAD7"), ("Sage", "#7F9A83"),
      ("Moss", "#778C58"), ("Slate Teal", "#254B5A"), ("Deep Spruce", "#082434")],
     "Outdoor and sustainability brands, wellness retreats, calm nature-led decks."),
    ("Desert Dunes",
     "Sun-baked sand and rich clay for warm, earthy storytelling.",
     "Earthy & Grounded",
     [("Dune Sand", "#E9DECE"), ("Wheat", "#E6CDA9"), ("Amber Clay", "#9D5F1B"),
      ("Cedar", "#6C3C0C"), ("Burnt Sienna", "#722A07"), ("Espresso", "#291602")],
     "Artisan and heritage brands, travel and hospitality, rustic product launches."),
    ("Serene Nature",
     "Soft botanicals and watery blues for a calm, natural feel.",
     "Earthy & Grounded",
     [("Cream", "#FDF1DB"), ("Oat", "#DFD5C6"), ("Seaglass", "#A6CBD3"),
      ("Fern", "#96AB88"), ("Lake Blue", "#4F8FA8"), ("Pine", "#597B60")],
     "Spa and wellness, eco products, gentle lifestyle content."),
    ("Mellow Greens",
     "Muted greens and warm clay for an understated organic palette.",
     "Earthy & Grounded",
     [("Petal Clay", "#F2D2C2"), ("Mist Green", "#D0DDD7"), ("Almond", "#C6A894"),
      ("Eucalyptus", "#A3BFB3"), ("Juniper", "#648E7B"), ("Graphite", "#6D6E71")],
     "Plant and garden brands, holistic services, soft editorial layouts."),

    # ---------------- Feminine & Soft ----------------
    ("Soft Crimson",
     "Tender creams deepening into berry and plum.",
     "Feminine & Soft",
     [("Linen", "#EEE8DC"), ("Shell", "#F5E8E0"), ("Rose Quartz", "#F8DEDC"),
      ("Dusty Rose", "#DAA2A1"), ("Wine Rose", "#914955"), ("Plum", "#683147")],
     "Beauty and bridal, boutique brands, romantic editorial decks."),
    ("Beautiful Blush",
     "Layered blush tones from porcelain to terracotta rose.",
     "Feminine & Soft",
     [("Porcelain", "#FEEEE8"), ("Petal", "#F9D3D0"), ("Ash Rose", "#C7BDBD"),
      ("Coral Blush", "#F2A7A2"), ("Clay Rose", "#C98685"), ("Terracotta Rose", "#C16B62")],
     "Beauty, skincare, lifestyle blogs, soft feminine product pages."),
    # NOTE: The Brand Alchemists published "Sunset Lovers" with hexes identical
    # to "Beautiful Blush". Rather than ship a duplicate, this palette is a
    # custom re-tint into a true golden-hour gradient so the name fits.
    ("Sunset Lovers",
     "A warm romantic gradient that runs from peach glow to plum dusk at golden hour.",
     "Feminine & Soft",
     [("Peach Glow", "#FFEAD6"), ("Golden Apricot", "#FBC98E"), ("Coral Sunset", "#F49A6E"),
      ("Burnt Coral", "#E76F51"), ("Raspberry Dusk", "#B5485E"), ("Plum Twilight", "#5C2A4D")],
     "Weddings and events, romance-led campaigns, warm invitations."),
    ("Salty Pink",
     "Sea-softened pinks and mauves with a cool gray edge.",
     "Feminine & Soft",
     [("Peach Salt", "#F8D4C1"), ("Shell Pink", "#F0C4C2"), ("Rosewood", "#D58C89"),
      ("Mauve", "#AE7F8A"), ("Driftwood", "#9C8C85"), ("Slate Mauve", "#6A6571")],
     "Coastal feminine brands, soft fashion, understated beauty content."),

    # ---------------- Coastal & Calm ----------------
    ("High Seas",
     "Deep ocean navy lifted by bright sea spray.",
     "Coastal & Calm",
     [("Sea Foam White", "#EDEDEE"), ("Cloud Blue", "#D6E0EA"), ("Harbor Gray", "#898989"),
      ("Tide", "#72A6B7"), ("Deep Marine", "#18617F"), ("Midnight Navy", "#092846")],
     "Maritime and travel brands, finance, trust-building corporate decks."),
    ("Calm Sapphire",
     "Cool sapphire blues for a composed, trustworthy mood.",
     "Coastal & Calm",
     [("Powder Blue", "#D6E0EA"), ("Cornflower", "#84A2C9"), ("Steel", "#898993"),
      ("Denim", "#445A79"), ("Sapphire", "#344E95"), ("Ink", "#1C1D37")],
     "Professional services, SaaS, consulting, dependable corporate content."),
    ("Around the Riverbend",
     "Riverstone neutrals with muted blue and sand.",
     "Coastal & Calm",
     [("River Mist", "#C5DAE6"), ("Pebble", "#BEBBC2"), ("Sand", "#BBA48D"),
      ("Sage Gray", "#9AA7A0"), ("Bluestone", "#8391A7"), ("Olive Gray", "#767064")],
     "Quiet lifestyle brands, architecture and interiors, calm reports."),
    ("Sandy Shores",
     "Warm shoreline sand against deep tidal blue.",
     "Coastal & Calm",
     [("Beach Sand", "#EFE6D6"), ("Driftwood", "#B8B8AC"), ("Toffee", "#CBA378"),
      ("Clay", "#C86D39"), ("Deep Tide", "#2E4C63"), ("Charcoal", "#2C2927")],
     "Coastal hospitality, travel, warm-meets-cool lifestyle decks."),

    # ---------------- Bold & Fun ----------------
    ("Summer Daze Pink",
     "Playful pinks and teals for an upbeat summer vibe.",
     "Bold & Fun",
     [("Cream Soda", "#F6E4D5"), ("Aqua Mist", "#C9E1E5"), ("Bubblegum", "#EFBAD6"),
      ("Magenta Pop", "#C55894"), ("Teal", "#389998"), ("Near Black", "#271F22")],
     "Youthful consumer brands, events, social-first campaigns."),
    ("Joyful Boho",
     "Bright boho mix of coral, sky, and deep teal.",
     "Bold & Fun",
     [("Apricot", "#F8D4BB"), ("Peach", "#FAC8C0"), ("Sky", "#B2D7E8"),
      ("Coral", "#D56F53"), ("Cornflower", "#5F8BC1"), ("Deep Teal", "#014552")],
     "Creative studios, festivals, lively product and travel content."),
    ("Fresh Fusion",
     "Fresh, energetic blend of pink, gold, and blue.",
     "Bold & Fun",
     [("Rose", "#F4CBD3"), ("Honey", "#F7CD9A"), ("Periwinkle", "#B8D3EE"),
      ("Salmon", "#EA9D9B"), ("Teal", "#599F9E"), ("Slate", "#808285")],
     "Modern lifestyle brands, food and drink, upbeat marketing decks."),
    ("Modern Pop",
     "High-contrast pop palette with electric magenta and blue.",
     "Bold & Fun",
     [("White", "#FFFFFF"), ("Turquoise", "#47BFBE"), ("Gray", "#898993"),
      ("Hot Pink", "#E83698"), ("Electric Blue", "#1C5AE4"), ("Black", "#000000")],
     "Tech and entertainment launches, bold campaigns, attention-grabbing slides."),

    # ---------------- Modern Boho & Neutrals ----------------
    ("Mystic Earth",
     "Soft mystic neutrals with warm tan and clay.",
     "Modern Boho & Neutrals",
     [("Pale Gray", "#D9D8DD"), ("Sand", "#D8BFAB"), ("Mauve Mist", "#D4C1C7"),
      ("Camel", "#E1BB94"), ("Taupe", "#9C8F89"), ("Walnut", "#73604D")],
     "Boho lifestyle brands, wellness, warm minimalist portfolios."),
    ("Modern Boho",
     "Airy boho neutrals with a soft clay accent.",
     "Modern Boho & Neutrals",
     [("Cloud", "#EDEDED"), ("Mist", "#E2E8E6"), ("Shell", "#F5E8E0"),
      ("Blush Clay", "#EFC6B4"), ("Tan", "#D5B295"), ("Sage Gray", "#9FB0AA")],
     "Interiors and decor, slow-living brands, calm neutral decks."),
    ("Sandy Neutrals",
     "Warm sand and rosy clay neutrals.",
     "Modern Boho & Neutrals",
     [("Shell", "#F5E8E0"), ("Peach Cream", "#EED3C2"), ("Rose Mist", "#F5D4D1"),
      ("Latte", "#C5B4A3"), ("Mushroom", "#A78F7C"), ("Cocoa", "#7F6152")],
     "Skincare and beauty, artisanal products, soft brand systems."),
    ("Perfectly Peach",
     "Soft peach warmed by deep charcoal grounding.",
     "Modern Boho & Neutrals",
     [("Peach Cream", "#FFF2EE"), ("Lilac Gray", "#D9CED6"), ("Apricot", "#F9C7A1"),
      ("Terracotta", "#D1835C"), ("Mauve Slate", "#60555D"), ("Charcoal", "#303437")],
     "Lifestyle brands, boutique services, warm editorial layouts."),

    # ---------------- Vintage Romance ----------------
    ("Gothic Vintage",
     "Dramatic vintage contrast — oxblood and forest on bone.",
     "Vintage Romance",
     [("Bone White", "#FFFFFF"), ("Silver", "#D9D9D9"), ("Parchment", "#DFC9B4"),
      ("Forest", "#263F2C"), ("Oxblood", "#4D0011"), ("Black", "#000000")],
     "Heritage and luxury brands, moody editorials, dramatic event decks."),
    ("Passionfruit Pie",
     "Rich vintage warmth of brass, wine, and cocoa.",
     "Vintage Romance",
     [("Ivory", "#F0EFEC"), ("Pewter", "#A9ACAD"), ("Brass", "#B28735"),
      ("Chestnut", "#866042"), ("Wine", "#702840"), ("Coffee", "#412F26")],
     "Wineries and spirits, antique and craft brands, warm vintage layouts."),
    ("Modern Mystic",
     "Romantic lilac and amber over deep aubergine.",
     "Vintage Romance",
     [("Cream", "#F5EAE1"), ("Pale Gray", "#D9D8DD"), ("Lilac", "#D7C2EE"),
      ("Amber", "#E4AD75"), ("Ochre", "#C07A35"), ("Aubergine", "#592E6B")],
     "Mystic and astrology brands, creative portfolios, romantic invitations."),
    ("Eclectic Muse",
     "Moody eclectic mix of camel, oxblood, and black.",
     "Vintage Romance",
     [("Eggshell", "#FFFCF1"), ("Peach", "#F1CBB8"), ("Camel", "#C9A475"),
      ("Olive Bronze", "#6E5A2F"), ("Oxblood", "#56140F"), ("Black", "#000000")],
     "Art and gallery brands, vintage fashion, characterful editorial decks."),

    # ---------------- Luxury & Sophisticated (Steph Corrigan) ----------------
    ("Warm Linen",
     "Refined warm neutrals from linen to chestnut.",
     "Luxury & Sophisticated",
     [("Ivory", "#F2F1EF"), ("Linen", "#D9D2CC"), ("Sand", "#D9B18E"),
      ("Clay", "#A67564"), ("Chestnut", "#723E31")],
     "Luxury neutrals branding, interiors, premium minimalist decks."),
    ("Emerald Manor",
     "Stately green and gold with a soft cream lift.",
     "Luxury & Sophisticated",
     [("White", "#F4F4F4"), ("Cream", "#EDDBCD"), ("Antique Gold", "#C0B283"),
      ("Forest", "#404A42"), ("Midnight", "#192231")],
     "Heritage luxury, law and finance, refined corporate identity."),
    ("Crimson Silk",
     "Soft blush rising to deep lacquer red.",
     "Luxury & Sophisticated",
     [("Shell", "#F3ECE4"), ("Rosewood", "#D9B6A3"), ("Coral Clay", "#D88B79"),
      ("Lacquer Red", "#A71F13"), ("Oxblood", "#340A10")],
     "Premium beauty, fashion houses, bold romantic luxury decks."),
    ("Midnight Harbor",
     "Inky navy warmed by sand and terracotta.",
     "Luxury & Sophisticated",
     [("Sand", "#EBDED4"), ("Apricot", "#D9AA90"), ("Terracotta", "#A65E46"),
      ("Navy", "#07203F"), ("Ink", "#02000D")],
     "Sophisticated tech and finance, premium travel, confident corporate slides."),
    ("Gilded Age",
     "Champagne and gold over deep oxblood.",
     "Luxury & Sophisticated",
     [("Champagne", "#D9C4A9"), ("Stone", "#D8D0C5"), ("Gold", "#D9B061"),
      ("Bronze", "#8D6F57"), ("Oxblood", "#3F0D0C")],
     "Luxury goods, jewelry, gala and event branding, opulent decks."),
    ("Velvet Teal",
     "Deep teal and near-black with a cool pearl lift.",
     "Luxury & Sophisticated",
     [("Ivory", "#F2EFEA"), ("Pearl", "#DFE5F3"), ("Teal", "#557373"),
      ("Bitter Olive", "#272401"), ("Black", "#0D0D0D")],
     "Modern luxury brands, premium hospitality, sleek editorial layouts."),
    ("Jewel Box",
     "Jewel tones — rose, teal, and olive on cream.",
     "Luxury & Sophisticated",
     [("Cream", "#E7DECD"), ("Sea Blue", "#62929E"), ("Raspberry", "#A6445D"),
      ("Olive", "#393A10"), ("Deep Teal", "#142F40")],
     "Boutique luxury, artful brands, rich colourful presentations."),
    ("Mauve Garden",
     "Mauve and deep garden green for quiet drama.",
     "Luxury & Sophisticated",
     [("Oat", "#D8C6BA"), ("Mauve", "#C09BAC"), ("Moss", "#617246"),
      ("Pine", "#314021"), ("Near Black", "#0C0D07")],
     "Floral and garden luxury, refined feminine brands, elegant decks."),
    ("Slate Mist",
     "Tranquil slate blues with a clean off-white.",
     "Luxury & Sophisticated",
     [("Mist White", "#F3F5F9"), ("Off White", "#F2F2F0"), ("Slate Blue", "#819FA7"),
      ("Deep Slate", "#5B6E74"), ("Black", "#0D0D0D")],
     "Calm professional brands, wellness-luxury, understated reports."),
    ("Quiet Luxury",
     "Understated grayscale with a soft mauve warmth.",
     "Luxury & Sophisticated",
     [("Soft White", "#F2F2F2"), ("Silver", "#D9D9D9"), ("Mauve Gray", "#BFAFAF"),
      ("Midnight", "#0F1B27"), ("Black", "#0D0D0D")],
     "Minimalist luxury, high-end fashion, restrained executive decks."),

    # ---------------- Iconic Brands ----------------
    # Publicly documented brand colors, provided as a design reference. All
    # trademarks and brand colors are property of their respective owners.
    ("Facebook",
     "The classic Facebook blue with its clean grayscale interface tones.",
     "Iconic Brands",
     [("Facebook Blue", "#1877F2"), ("Royal Blue", "#4267B2"), ("Cloud Gray", "#F0F2F5"),
      ("Near Black", "#1C1E21"), ("White", "#FFFFFF")],
     "Social and community products, tech UIs, friendly corporate decks."),
    ("Instagram",
     "Instagram's signature sunset gradient from royal blue through pink to gold.",
     "Iconic Brands",
     [("Royal Blue", "#405DE6"), ("Purple", "#833AB4"), ("Dark Pink", "#C13584"),
      ("Purple-Red", "#E1306C"), ("Dark Orange", "#F56040"), ("Yellow", "#FCAF45")],
     "Creator and social campaigns, vibrant marketing, lifestyle brands."),
    ("Twitter X",
     "Twitter's bright blue and the X-era near-black, with cool UI grays.",
     "Iconic Brands",
     [("Twitter Blue", "#1DA1F2"), ("Slate", "#657786"), ("Light Gray", "#E1E8ED"),
      ("Ink Black", "#14171A"), ("White", "#FFFFFF")],
     "News and media, real-time products, clean tech presentations."),
    ("Tesla",
     "Torch red against carbon black and silver — sleek electric minimalism.",
     "Iconic Brands",
     [("White", "#FFFFFF"), ("Silver", "#E6E7E8"), ("Torch Red", "#E82127"),
      ("Steel Gray", "#5C5E62"), ("Carbon", "#181B21")],
     "Automotive and hardware, premium tech, bold minimalist decks."),
    ("McDonalds",
     "The golden arches: bright yellow and Mickey-D red on near-black.",
     "Iconic Brands",
     [("Golden Yellow", "#FFC72C"), ("Mickey D Red", "#DA291C"),
      ("Charcoal", "#27251F"), ("White", "#FFFFFF")],
     "Food and QSR brands, family-friendly campaigns, high-energy promos."),
    ("Nike",
     "Just black and white with the unmistakable Volt accent.",
     "Iconic Brands",
     [("Black", "#111111"), ("Cool Gray", "#8D8D8D"), ("Volt", "#CEFF00"),
      ("White", "#FFFFFF")],
     "Sportswear and fitness, bold athletic campaigns, high-contrast decks."),
    ("Spotify",
     "Spotify's vivid green against deep black.",
     "Iconic Brands",
     [("Spotify Green", "#1DB954"), ("Bright Green", "#1ED760"),
      ("Spotify Black", "#191414"), ("White", "#FFFFFF")],
     "Music and audio, youthful tech products, energetic marketing."),
    ("Google",
     "Google's four primaries: blue, red, yellow, and green.",
     "Iconic Brands",
     [("Google Blue", "#4285F4"), ("Google Red", "#DB4437"), ("Google Yellow", "#F4B400"),
      ("Google Green", "#0F9D58"), ("White", "#FFFFFF")],
     "Consumer tech, friendly product UIs, approachable corporate decks."),
    ("Netflix",
     "Netflix red and dark red over cinema black.",
     "Iconic Brands",
     [("Netflix Red", "#E50914"), ("Dark Red", "#B81D24"),
      ("Cinema Black", "#221F1F"), ("White", "#FFFFFF")],
     "Entertainment and streaming, dramatic launches, cinematic decks."),
    ("Coca-Cola",
     "The timeless Coca-Cola red with crisp black and white.",
     "Iconic Brands",
     [("Coca-Cola Red", "#F40009"), ("Crimson", "#B30000"),
      ("Black", "#000000"), ("White", "#FFFFFF")],
     "Beverage and FMCG, classic mass-market campaigns, bold retail."),
    ("Slack",
     "Slack's aubergine with its playful four-color accent set.",
     "Iconic Brands",
     [("Aubergine", "#4A154B"), ("Blue", "#36C5F0"), ("Green", "#2EB67D"),
      ("Yellow", "#ECB22E"), ("Red", "#E01E5A")],
     "Productivity and SaaS, playful B2B brands, collaborative product decks."),
    ("Starbucks",
     "Starbucks' siren green in deep and house-green tones.",
     "Iconic Brands",
     [("Starbucks Green", "#00704A"), ("House Green", "#1E3932"), ("Accent Green", "#006241"),
      ("Cream", "#F1F8F5"), ("White", "#FFFFFF")],
     "Cafe and hospitality, premium retail, warm lifestyle branding."),
    ("Amazon",
     "Amazon orange and squid-ink navy with a trusted link blue.",
     "Iconic Brands",
     [("Amazon Orange", "#FF9900"), ("Squid Ink", "#232F3E"), ("Link Blue", "#146EB4"),
      ("Light Gray", "#F2F3F3"), ("White", "#FFFFFF")],
     "E-commerce and logistics, trusted marketplace UIs, retail decks."),
    ("Airbnb",
     "Airbnb's Rausch coral with Babu teal and warm neutrals.",
     "Iconic Brands",
     [("Rausch", "#FF5A5F"), ("Babu Teal", "#00A699"), ("Arches", "#FC642D"),
      ("Hof", "#484848"), ("Foggy", "#767676")],
     "Travel and hospitality, community marketplaces, warm lifestyle brands."),

    # ---------------- Editor Classics (Dark) ----------------
    # Official published palettes from each theme's spec. Mode 'dark' means the
    # darkest color is the editor background and the lightest is the foreground.
    ("Dracula",
     "The iconic dark theme: deep slate background with vivid purple, pink, and cyan.",
     "Editor Classics (Dark)",
     [("Background", "#282A36"), ("Foreground", "#F8F8F2"), ("Purple", "#BD93F9"),
      ("Pink", "#FF79C6"), ("Green", "#50FA7B"), ("Cyan", "#8BE9FD")],
     "Developer tools, dark dashboards, technical decks, hacker-aesthetic slides.",
     "dark"),
    ("One Dark Pro",
     "Atom's beloved One Dark: balanced contrast with soft blue, red, and green.",
     "Editor Classics (Dark)",
     [("Background", "#282C34"), ("Foreground", "#ABB2BF"), ("Blue", "#61AFEF"),
      ("Red", "#E06C75"), ("Green", "#98C379"), ("Purple", "#C678DD")],
     "Developer products, code-forward presentations, engineering docs.",
     "dark"),
    ("Monokai",
     "The classic Sublime palette: warm charcoal with hot pink, lime, and cyan.",
     "Editor Classics (Dark)",
     [("Background", "#272822"), ("Foreground", "#F8F8F2"), ("Pink", "#F92672"),
      ("Green", "#A6E22E"), ("Cyan", "#66D9EF"), ("Orange", "#FD971F")],
     "Developer brands, vibrant code demos, energetic technical talks.",
     "dark"),
    ("Nord",
     "Arctic, north-bluish palette — calm frost blues over polar night.",
     "Editor Classics (Dark)",
     [("Polar Night", "#2E3440"), ("Snow Storm", "#ECEFF4"), ("Frost", "#88C0D0"),
      ("Deep Frost", "#5E81AC"), ("Aurora Green", "#A3BE8C"), ("Aurora Red", "#BF616A")],
     "Calm developer UIs, minimalist tech decks, design-system documentation.",
     "dark"),
    ("Gruvbox Dark",
     "Retro warm-earth palette with a cult following — orange, red, and lime on coffee.",
     "Editor Classics (Dark)",
     [("Background", "#282828"), ("Foreground", "#EBDBB2"), ("Orange", "#FE8019"),
      ("Red", "#FB4934"), ("Green", "#B8BB26"), ("Yellow", "#FABD2F")],
     "Retro-leaning dev brands, terminal aesthetics, cozy technical content.",
     "dark"),
    ("Tokyo Night",
     "A downtown-at-night palette: deep indigo with neon blue and purple.",
     "Editor Classics (Dark)",
     [("Background", "#1A1B26"), ("Foreground", "#C0CAF5"), ("Blue", "#7AA2F7"),
      ("Purple", "#BB9AF7"), ("Cyan", "#7DCFFF"), ("Green", "#9ECE6A")],
     "Modern developer products, sleek dark dashboards, night-mode decks.",
     "dark"),
    ("Catppuccin Mocha",
     "The wildly popular pastel dark theme — soothing mauve, pink, and blue.",
     "Editor Classics (Dark)",
     [("Base", "#1E1E2E"), ("Text", "#CDD6F4"), ("Mauve", "#CBA6F7"),
      ("Pink", "#F5C2E7"), ("Blue", "#89B4FA"), ("Green", "#A6E3A1")],
     "Cozy developer UIs, community tools, friendly technical presentations.",
     "dark"),
    ("Night Owl",
     "Sarah Drasner's theme tuned for low light — deep navy with coral and teal.",
     "Editor Classics (Dark)",
     [("Background", "#011627"), ("Foreground", "#D6DEEB"), ("Blue", "#82AAFF"),
      ("Coral", "#F78C6C"), ("Green", "#C5E478"), ("Purple", "#C792EA")],
     "Accessible dark UIs, late-night dev tools, low-light presentations.",
     "dark"),
    ("GitHub Dark",
     "GitHub's own dark mode — the syntax colors powering github.com.",
     "Editor Classics (Dark)",
     [("Canvas", "#0D1117"), ("Foreground", "#C9D1D9"), ("Blue", "#58A6FF"),
      ("Green", "#3FB950"), ("Red", "#F85149"), ("Purple", "#BC8CFF")],
     "Open-source projects, developer platforms, code-review and docs UIs.",
     "dark"),
    ("Solarized Dark",
     "Ethan Schoonover's precision palette — teal-black base with measured accents.",
     "Editor Classics (Dark)",
     [("Base03", "#002B36"), ("Base0", "#839496"), ("Blue", "#268BD2"),
      ("Cyan", "#2AA198"), ("Green", "#859900"), ("Magenta", "#D33682")],
     "Long-form reading UIs, scientific tools, precise technical documentation.",
     "dark"),

    # ---------------- Editor Light ----------------
    ("GitHub Light",
     "GitHub's default light mode — clean white with crisp functional accents.",
     "Editor Light",
     [("Canvas", "#FFFFFF"), ("Ink", "#24292F"), ("Blue", "#0969DA"),
      ("Green", "#1A7F37"), ("Red", "#CF222E"), ("Purple", "#8250DF")],
     "Documentation sites, developer platforms, clean technical decks.",
     "light"),
    ("Solarized Light",
     "The warm-paper counterpart to Solarized Dark — cream base, calm accents.",
     "Editor Light",
     [("Base3", "#FDF6E3"), ("Body", "#586E75"), ("Blue", "#268BD2"),
      ("Cyan", "#2AA198"), ("Red", "#DC322F"), ("Green", "#859900")],
     "Readable docs, academic writing, easy-on-the-eyes light presentations.",
     "light"),
    ("Atom One Light",
     "Atom's light theme — bright neutral canvas with friendly saturated accents.",
     "Editor Light",
     [("Canvas", "#FAFAFA"), ("Ink", "#383A42"), ("Blue", "#4078F2"),
      ("Red", "#E45649"), ("Green", "#50A14F"), ("Purple", "#A626A4")],
     "Approachable developer docs, tutorials, clean product UIs.",
     "light"),
    ("Catppuccin Latte",
     "Catppuccin's light flavor — soft pastel canvas with cheerful accents.",
     "Editor Light",
     [("Base", "#EFF1F5"), ("Text", "#4C4F69"), ("Mauve", "#8839EF"),
      ("Pink", "#EA76CB"), ("Blue", "#1E66F5"), ("Green", "#40A02B")],
     "Friendly light UIs, community docs, warm technical content.",
     "light"),
    ("Rosé Pine Dawn",
     "A soho-boutique light theme — misty rose canvas with muted jewel accents.",
     "Editor Light",
     [("Base", "#FAF4ED"), ("Text", "#575279"), ("Rose", "#D7827E"),
      ("Gold", "#EA9D34"), ("Pine", "#286983"), ("Iris", "#907AA9")],
     "Elegant developer portfolios, refined docs, soft editorial-tech decks.",
     "light"),

    # ---------------- Neon & Retro ----------------
    ("Synthwave 84",
     "Retro-futuristic neon — glowing hot pink and cyan over deep purple-night.",
     "Neon & Retro",
     [("Background", "#262335"), ("Foreground", "#F0EFF1"), ("Hot Pink", "#FF7EDB"),
      ("Cyan", "#36F9F6"), ("Orange", "#FF8B39"), ("Yellow", "#FEDE5D")],
     "80s-retro brands, bold product launches, high-energy creative decks.",
     "dark"),
    ("Cobalt2",
     "Wes Bos's signature theme — deep blue with electric yellow and orange.",
     "Neon & Retro",
     [("Background", "#193549"), ("White", "#FFFFFF"), ("Yellow", "#FFC600"),
      ("Blue", "#0088FF"), ("Orange", "#FF9D00"), ("Green", "#3AD900")],
     "Bold developer brands, course and tutorial content, punchy tech talks.",
     "dark"),
    ("Shades of Purple",
     "A bold purple-forward theme with gold and cyan pops.",
     "Neon & Retro",
     [("Background", "#2D2B55"), ("White", "#FFFFFF"), ("Yellow", "#FAD000"),
      ("Purple", "#B362FF"), ("Cyan", "#9EFFFF"), ("Pink", "#FF628C")],
     "Playful tech brands, creative coding, vibrant product showcases.",
     "dark"),
    ("Spaceduck",
     "A spacefaring palette — inky cosmos with teal, lavender, and cream.",
     "Neon & Retro",
     [("Background", "#0F111B"), ("Cream", "#ECF0C1"), ("Teal", "#00A3CC"),
      ("Lavender", "#B3A1E6"), ("Green", "#5CCC96"), ("Gold", "#E39400")],
     "Sci-fi and space brands, futuristic dashboards, moody tech decks.",
     "dark"),
    ("Horizon",
     "A warm sunset-on-dark palette — rose and coral against deep charcoal.",
     "Neon & Retro",
     [("Background", "#1C1E26"), ("Foreground", "#D5D8DA"), ("Rose", "#E95678"),
      ("Coral", "#FAB795"), ("Cyan", "#59E1E3"), ("Purple", "#B877DB")],
     "Warm-toned dev brands, creative tools, stylish dark presentations.",
     "dark"),

    # ---------------- Obsidian & Calm ----------------
    # Everforest / Catppuccin have official specs; the Obsidian-native themes
    # (Things, Minimal, Blue Topaz, Primary, AnuPpuccin) are highly customizable,
    # so these are faithful approximations of each theme's signature look.
    ("Everforest",
     "A soft, low-contrast forest palette — sage green and warm gold on deep pine.",
     "Obsidian & Calm",
     [("Background", "#2D353B"), ("Foreground", "#D3C6AA"), ("Green", "#A7C080"),
      ("Yellow", "#DBBC7F"), ("Orange", "#E69875"), ("Aqua", "#83C092")],
     "Calm note-taking UIs, wellness-tech, gentle low-contrast documentation.",
     "dark"),
    ("Things",
     "Inspired by the Things app — crisp white with a single confident blue.",
     "Obsidian & Calm",
     [("Paper", "#FFFFFF"), ("Ink", "#1C1C1E"), ("Things Blue", "#0098FF"),
      ("Soft Gray", "#EAECEF"), ("Slate", "#6E7178"), ("Coral", "#FF5A4D")],
     "Clean productivity apps, minimalist note UIs, focused light decks.",
     "light"),
    ("Minimal",
     "The Obsidian favorite — neutral grays with one calm configurable accent.",
     "Obsidian & Calm",
     [("Paper", "#FFFFFF"), ("Text", "#2E3338"), ("Accent Blue", "#4C8BF5"),
      ("Light Gray", "#F5F6F8"), ("Border Gray", "#D5D8DC"), ("Muted", "#9AA0A6")],
     "Distraction-free writing, clean knowledge bases, restrained light UIs.",
     "light"),
    ("Blue Topaz",
     "A muted, relaxed blue-teal palette — calm and easy to live in.",
     "Obsidian & Calm",
     [("Mist", "#EEF3F6"), ("Ink", "#2C3E50"), ("Topaz Blue", "#2E86AB"),
      ("Teal", "#3AAFA9"), ("Slate", "#5D7A8C"), ("Sand", "#D9E2E8")],
     "Research vaults, calm reading UIs, understated knowledge work.",
     "light"),
    ("Primary",
     "Soft and relaxing out of the box — warm cream with a friendly blue.",
     "Obsidian & Calm",
     [("Cream", "#FAF8F4"), ("Charcoal", "#3B3A39"), ("Primary Blue", "#3E7BFA"),
      ("Warm Gray", "#ECE9E4"), ("Stone", "#A8A29E"), ("Clay", "#D98E73")],
     "Cozy personal knowledge bases, journaling apps, warm light decks.",
     "light"),
    ("AnuPpuccin",
     "A Catppuccin-based theme loaded with rainbow accents over a pastel night.",
     "Obsidian & Calm",
     [("Base", "#1E1E2E"), ("Text", "#CDD6F4"), ("Peach", "#FAB387"),
      ("Green", "#A6E3A1"), ("Blue", "#89B4FA"), ("Mauve", "#CBA6F7")],
     "Colorful note systems, expressive dashboards, playful dark UIs.",
     "dark"),

    # ---------------- Master Painters ----------------
    # Palettes DERIVED from each artist's iconic work (dominant colors hand-
    # picked), not official specs. Most source works are in the public domain;
    # the palettes here are evocations for design use.
    ("Rothko",
     "Color-field intensity from Orange, Red, Yellow — molten reds glowing over warm dark.",
     "Master Painters",
     [("Warm Black", "#1C1310"), ("Maroon", "#6E1A12"), ("Vermilion", "#C8451B"),
      ("Amber", "#D98B2B"), ("Marigold", "#E8A22B"), ("Cream", "#F2E3C6")],
     "Bold gallery decks, emotive brand stories, dramatic editorial spreads.",
     "dark"),
    ("Pollock",
     "The drip energy of Autumn Rhythm — bone canvas tangled with black, rust, and teal.",
     "Master Painters",
     [("Bone", "#F5F0E6"), ("Canvas", "#E8DFC8"), ("Teal Splash", "#2E6E6A"),
      ("Rust", "#A6522C"), ("Umber", "#6B4A2B"), ("Black", "#1A1714")],
     "Creative studios, expressive portfolios, energetic abstract layouts.",
     "light"),
    ("Picasso Blue Period",
     "Melancholy blues of The Old Guitarist — somber and soulful, lit by a single ochre.",
     "Master Painters",
     [("Deep Blue", "#0B2A4A"), ("Teal-Blue", "#14506E"), ("Steel", "#2E7A99"),
      ("Blue-Gray", "#A8B6BE"), ("Muted Ochre", "#C7A26B")],
     "Reflective brand stories, fine-art decks, moody editorial design.",
     "dark"),
    ("Picasso Rose Period",
     "The tender warmth of the Rose Period — circus pinks and terracotta over soft beige.",
     "Master Painters",
     [("Warm Beige", "#E5D2B8"), ("Soft Pink", "#E8B7A6"), ("Rose", "#D98C7A"),
      ("Terracotta", "#C86B4A"), ("Blue-Gray", "#8A9BA0"), ("Clay Brown", "#8A4B33")],
     "Warm lifestyle brands, gentle editorial, romantic gallery layouts.",
     "light"),
    ("Rembrandt",
     "Chiaroscuro drama — golden light emerging from deep umber shadow.",
     "Master Painters",
     [("Near Black", "#1A140E"), ("Umber", "#3D2B1A"), ("Oxblood", "#6E2018"),
      ("Raw Sienna", "#8A5A22"), ("Golden Ochre", "#C68A3A"), ("Ivory", "#E8D5A8")],
     "Luxury heritage brands, museum and gallery decks, refined dark layouts.",
     "dark"),
    ("Van Gogh",
     "The swirling night of The Starry Night — cobalt and indigo lit by golden stars.",
     "Master Painters",
     [("Indigo Night", "#0B1A3A"), ("Cypress", "#1A3A2A"), ("Cobalt", "#1E4A8A"),
      ("Swirl Blue", "#4A78B5"), ("Pale Moon", "#E8E2B0"), ("Star Yellow", "#F4C430")],
     "Expressive brands, creative campaigns, vivid storytelling decks.",
     "dark"),
    ("Monet",
     "Impressionist calm from Water Lilies — soft greens, mist, and floating mauve.",
     "Master Painters",
     [("Cream", "#E8DCC0"), ("Willow", "#A8C5B0"), ("Misty Blue", "#6E9AA6"),
      ("Lily Mauve", "#D6B8CE"), ("Lily Pink", "#C76B8E"), ("Pond Teal", "#2E5A6E")],
     "Wellness and spa brands, soft lifestyle, serene editorial design.",
     "light"),
    ("Klimt",
     "The shimmer of The Kiss — gold leaf and jewel tones over velvet black.",
     "Master Painters",
     [("Black", "#1A1610"), ("Jewel Green", "#4A6B4E"), ("Terracotta", "#B5613A"),
      ("Deep Gold", "#9A7B1E"), ("Gold Leaf", "#C8A02C"), ("Ivory", "#EDE2C4")],
     "Luxury and beauty brands, opulent invitations, decorative gallery decks.",
     "dark"),
    ("Vermeer",
     "The quiet light of Girl with a Pearl Earring — ultramarine and ochre in shadow.",
     "Master Painters",
     [("Umber Ground", "#2A2018"), ("Ultramarine", "#1F4E8C"), ("Ochre Turban", "#C8912E"),
      ("Warm Flesh", "#D8A985"), ("Ivory", "#EAD9B8")],
     "Refined editorial, premium brands, contemplative fine-art layouts.",
     "dark"),
    ("Hokusai",
     "The crashing blues of The Great Wave — Prussian indigo against a pale sky.",
     "Master Painters",
     [("Foam White", "#F2EFE6"), ("Sky Cream", "#E4D9B8"), ("Beige", "#C9B68A"),
      ("Indigo", "#2E5E8C"), ("Prussian Blue", "#1B3A6B"), ("Deep Navy", "#14233F")],
     "Travel and maritime brands, bold minimalist decks, Japandi-style design.",
     "light"),
    ("Matisse",
     "Fauvist joy from The Dance — flat, fearless terracotta, cobalt, and green.",
     "Master Painters",
     [("Cream", "#EFE6D2"), ("Flesh", "#D98C5A"), ("Pink", "#E0728C"),
      ("Terracotta", "#C8472C"), ("Kelly Green", "#3A8C4E"), ("Cobalt", "#2E6BB0")],
     "Playful creative brands, bold campaigns, vibrant cut-out style layouts.",
     "light"),
    ("Frida Kahlo",
     "Vivid Mexican folk color — cobalt, viridian, scarlet, and marigold in full bloom.",
     "Master Painters",
     [("Bone", "#EDE3D0"), ("Marigold", "#E89B1C"), ("Scarlet", "#C8262C"),
      ("Magenta", "#B5277A"), ("Cobalt", "#2E5EAA"), ("Viridian", "#1F7A4D")],
     "Festive brands, cultural campaigns, bold expressive editorial.",
     "light"),
    ("Mondrian",
     "De Stijl in its purest form — primary red, blue, and yellow gridded by black.",
     "Master Painters",
     [("White", "#F4F3EE"), ("Yellow", "#F2C200"), ("Red", "#D5212E"),
      ("Blue", "#1E3A8A"), ("Black", "#14110E")],
     "Graphic-forward brands, bold modernist decks, design-school aesthetics.",
     "light"),

    # ---------------- Directors & Cinematographers ----------------
    # Palettes DERIVED from each filmmaker's signature look across their iconic
    # work — evocations for design use, not official specs. Names belong to the
    # respective artists.
    ("Spielberg",
     "Warm nostalgic wonder — golden amber glow against deep teal night (E.T., Close Encounters).",
     "Directors & Cinematographers",
     [("Night Teal", "#13303A"), ("Shadow Teal", "#1F4A52"), ("Sky", "#7FB0B8"),
      ("Amber Glow", "#E0A23C"), ("Golden", "#F2C879"), ("Cream Light", "#F5E8C8")],
     "Heartfelt brand stories, family and adventure content, cinematic decks.",
     "dark"),
    ("Scorsese",
     "Operatic crimson and gold over black — the saturated heat of Goodfellas and Mean Streets.",
     "Directors & Cinematographers",
     [("Black", "#120A0A"), ("Oxblood", "#4A0E10"), ("Crimson", "#A11217"),
      ("Scarlet", "#D6322B"), ("Gold", "#C8972E"), ("Warm Ivory", "#E8D6B8")],
     "Bold dramatic brands, nightlife and culture, high-impact storytelling.",
     "dark"),
    ("Nolan",
     "Cold desaturated steel — gunmetal and slate blue, IMAX-scale and serious (Inception, Tenet).",
     "Directors & Cinematographers",
     [("Gunmetal", "#14181C"), ("Slate", "#2A333A"), ("Steel Blue", "#46606E"),
      ("Cold Blue", "#6E8A99"), ("Pale Steel", "#A9BCC4"), ("Bone", "#D8DEE0")],
     "Tech and thriller brands, serious corporate decks, modern minimal UIs.",
     "dark"),
    ("Deakins",
     "Orange-and-teal mastery — burnt ember against deep teal shadow (Blade Runner 2049, Sicario).",
     "Directors & Cinematographers",
     [("Black", "#0E0F12"), ("Teal Shadow", "#163A3E"), ("Teal", "#2E6E72"),
      ("Ember Orange", "#D8662A"), ("Amber Haze", "#E89B3C"), ("Dust", "#E8C99A")],
     "Cinematic brand films, dramatic product launches, atmospheric decks.",
     "dark"),
    ("Slocombe",
     "Golden adventure glow — rich ochre and warm brown of the Indiana Jones trilogy.",
     "Directors & Cinematographers",
     [("Jungle Shadow", "#1C1A10"), ("Deep Brown", "#3A2A16"), ("Olive", "#6B5A2A"),
      ("Ochre", "#B5852E"), ("Golden", "#E0A93C"), ("Warm Sand", "#EAD7A8")],
     "Adventure and travel brands, heritage storytelling, warm epic decks.",
     "dark"),
    ("Kubrick",
     "Stark, symmetrical dread — Overlook cream and burnt orange cut by carpet red (The Shining).",
     "Directors & Cinematographers",
     [("Cream", "#E8E0CC"), ("Bone", "#D8CBA8"), ("Burnt Orange", "#C8642A"),
      ("Carpet Red", "#B01F2E"), ("Brown", "#6E4A2A"), ("Black", "#1A1410")],
     "Bold retro brands, design-led decks, striking editorial layouts.",
     "light"),
    ("Tarantino",
     "Pulp-bold pop — Kill Bill yellow slashed with blood red and black.",
     "Directors & Cinematographers",
     [("Kill Yellow", "#FCE300"), ("Cream", "#F4ECCB"), ("Blood Red", "#B81414"),
      ("Crimson", "#7A0E0E"), ("Steel", "#4A4A4A"), ("Black", "#161210")],
     "High-energy brands, bold campaigns, attention-grabbing graphic decks.",
     "light"),
    ("Fincher",
     "Sickly desaturated green-cyan and sodium amber in deep shadow (Se7en, Fight Club).",
     "Directors & Cinematographers",
     [("Black Green", "#0E1310"), ("Dark Slate", "#1C2622"), ("Murk Green", "#3E4A38"),
      ("Cyan Steel", "#4A6660"), ("Sodium Amber", "#9A7B3A"), ("Ash", "#B8BEB4")],
     "Tech-noir brands, moody product UIs, tense cinematic storytelling.",
     "dark"),
    ("Lubezki",
     "Natural light at the edge of cold — snowy blue-gray lit by a single ember (The Revenant).",
     "Directors & Cinematographers",
     [("Cold Slate", "#1E262B"), ("Blue Gray", "#3A4A52"), ("Frost", "#6E828A"),
      ("Ember", "#B5662E"), ("Pale Sky", "#A8BAC0"), ("Bone", "#D6DBD8")],
     "Naturalistic brand films, outdoor and wellness, atmospheric editorial.",
     "dark"),
    ("Storaro",
     "Bold color-theory saturation — amber, crimson, and deep cyan (Apocalypse Now, The Conformist).",
     "Directors & Cinematographers",
     [("Jungle Black", "#10160F"), ("Deep Cyan", "#14484E"), ("Teal", "#2E7A78"),
      ("Crimson", "#C0281E"), ("Amber", "#E08A2A"), ("Gold", "#E8B84A")],
     "Expressive brands, art-house aesthetics, vivid symbolic color decks.",
     "dark"),
    ("Wong Kar-wai",
     "Lush, smoky saturation — deep red and emerald with gold (In the Mood for Love).",
     "Directors & Cinematographers",
     [("Noir Black", "#161010"), ("Deep Red", "#6E121A"), ("Crimson", "#A81C24"),
      ("Emerald", "#1E6E54"), ("Gold", "#C8972E"), ("Warm Cream", "#E8D2A8")],
     "Romantic and luxury brands, moody fashion, richly saturated editorial.",
     "dark"),
    ("Gordon Willis",
     "The 'Prince of Darkness' — golden amber emerging from near-black shadow (The Godfather).",
     "Directors & Cinematographers",
     [("Shadow Black", "#120D08"), ("Deep Brown", "#2E1F12"), ("Sepia", "#5A3E22"),
      ("Amber", "#9A6A2A"), ("Golden Ochre", "#C89A48"), ("Warm Ivory", "#E6D2A8")],
     "Heritage luxury, prestige brand storytelling, low-key dramatic decks.",
     "dark"),
    ("Villeneuve",
     "Monumental desert minimalism — sand and spice ochre with cold slate (Dune).",
     "Directors & Cinematographers",
     [("Bone", "#F0E6CE"), ("Sand", "#E8D2A6"), ("Dune Ochre", "#C89A5A"),
      ("Spice Amber", "#C8762E"), ("Slate Blue", "#5A6E7A"), ("Charcoal", "#2A2622")],
     "Epic minimalist brands, sci-fi and architecture, monumental decks.",
     "light"),
]


def theme_mode(theme):
    """Optional 6th tuple element: 'dark' or 'light' (default 'light')."""
    return theme[5] if len(theme) > 5 else "light"


def render(theme):
    name, desc, category, colors, best_for = theme[:5]
    mode = theme_mode(theme)
    header_font, body_font = CATEGORY_FONTS[category]

    # Light themes run lightest -> darkest (background -> text); dark themes run
    # darkest -> lightest (background -> foreground).
    ordered = sorted(colors, key=lambda c: luminance(c[1]),
                     reverse=(mode != "dark"))
    ladder_set = LADDERS[mode]
    ladder = ladder_set.get(len(ordered), ladder_set[6])

    lines = [f"# {name}", "", desc, "", "## Color Palette", ""]
    for (cname, chex), role in zip(ordered, ladder):
        lines.append(f"- **{cname}**: `{chex.upper()}` - {role}")
    lines += [
        "",
        "## Typography",
        "",
        f"- **Headers**: {header_font} (use {header_font} Bold for emphasis)",
        f"- **Body Text**: {body_font}",
        "",
        "## Best Used For",
        "",
        best_for,
        "",
        f"> Category: {category}  ·  Mode: {mode}",
        "",
    ]
    return "\n".join(lines)


def main():
    os.makedirs(THEMES_DIR, exist_ok=True)
    for theme in THEMES:
        slug = slugify(theme[0])
        path = os.path.join(THEMES_DIR, f"{slug}.md")
        with open(path, "w") as f:
            f.write(render(theme))
    print(f"Wrote {len(THEMES)} theme files to {THEMES_DIR}")


if __name__ == "__main__":
    main()
