import json
import argparse
from pathlib import Path

VBA_TEMPLATE = """
Function GetRecordUrls() As Object
    ' Generated by generate_linking_macro.py
    Dim dict As Object
    Set dict = CreateObject("Scripting.Dictionary")
    
{lines}

    Set GetRecordUrls = dict
End Function
"""

def generate_vba(mapping_path, output_path):
    with open(mapping_path, 'r') as f:
        mapping = json.load(f)
        
    lines = []
    for citation, url in mapping.items():
        # Escape quotes
        safe_cite = citation.replace('"', '""')
        safe_url = url.replace('"', '""')
        line = f'    dict.Add "{safe_cite}", "{safe_url}"'
        lines.append(line)
        
    vba_code = VBA_TEMPLATE.format(lines="\n".join(lines))
    
    with open(output_path, 'w') as f:
        f.write(vba_code)
        
    print(f"Generated VBA function at {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate VBA macro for linking citations.")
    parser.add_argument("mapping_file", help="JSON file containing 'Citation': 'URL' pairs.")
    parser.add_argument("--output", default="LinkCitations.vba", help="Output VBA file.")
    args = parser.parse_args()
    
    generate_vba(args.mapping_file, args.output)
