#!/usr/bin/env bash
# 1-research.sh — NotebookLM ingest of product page → factset.md
# Reads product URL, ingests into NotebookLM (or local fallback), extracts:
#   - key benefits + active ingredients
#   - clinical / factual claims
#   - brand voice excerpt
# Writes: workdir/1-research/factset.md
#
# DEPS: notebooklm-research skill (preferred) OR direct curl + Gemini fallback

set -uo pipefail
SD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SD/_args.sh"
. "$SD/_siblings.sh"

[ -z "$WORKDIR" ] && { echo "missing --workdir" >&2; exit 1; }
OUT="$WORKDIR/1-research/factset.md"
mkdir -p "$(dirname "$OUT")"

# Try notebooklm-research sibling skill first
if [ -n "$FUTRGROUP_NOTEBOOKLM_SH" ] && [ -x "$FUTRGROUP_NOTEBOOKLM_SH" ] && [ -n "$PRODUCT_URL" ]; then
  echo "[1-research] using notebooklm-research sibling skill"
  "$FUTRGROUP_NOTEBOOKLM_SH" --url "$PRODUCT_URL" --questions "What are the key benefits and active ingredients?,What clinical/factual claims appear?,What does the brand promise to the customer?" --out "$OUT" 2>&1 | tail -3
else
  # Fallback: write a stub factset that downstream stages can run with
  echo "[FUTRGROUP] WARNING: notebooklm-research not configured (FUTRGROUP_NOTEBOOKLM_SH) — writing stub factset" >&2
  cat > "$OUT" <<EOF
# Factset stub — $BRAND
> Generated by futrgroup-v5/1-research.sh ($(date -u +%FT%TZ))
> TODO: wire notebooklm-research skill OR add Gemini fallback fetch.

## Source
$PRODUCT_URL

## Brand
$BRAND

## Provisional facts (replace with NotebookLM extract)
- Key benefit 1 (claim)
- Key benefit 2 (mechanism)
- Key ingredient
- Brand voice: ${STYLE:-default}

## Suggested questions for NotebookLM
- How do the active ingredients work?
- What clinical claims back the product?
- Who is the target audience?
- What is the price point?
EOF
fi

# Append brand DNA excerpt (best-effort)
FUTRGROUP_BRAND_HOME="${FUTRGROUP_BRAND_HOME:-$HOME/.futrgroup/brands}"
for p in "$FUTRGROUP_BRAND_HOME/$BRAND/BRAND-DNA.md" "$FUTRGROUP_BRAND_HOME/$BRAND/DNA.json" "$FUTRGROUP_BRAND_HOME/$BRAND/core.md"; do
  if [ -f "$p" ]; then
    {
      echo ""
      echo "## Brand DNA excerpt (auto-loaded from $(basename "$p"))"
      echo ""
      head -c 1200 "$p"
    } >> "$OUT"
    break
  fi
done

echo "[1-research] OK → $OUT"
exit 0
